spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    serviceUrl:
     defaultZone: http://peer1:1111/eureka_server/eureka/,http://peer1:1112/eureka_server/eureka/
server:
  port: 9010
